project:
  type: book
  output-dir: docs

book:
  title: "Your Book Title"
  author: "Your Name"
  date: last-modified
  date-format: "[Last updated:] YYYY-MM-DD"
  repo-url: https://github.com/UCD-SERG/quarto-book-template
  repo-actions: [edit, source, issue]
  downloads: [pdf, epub, docx]
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    number-sections: true
    embed-resources: false
  pdf:
    geometry:
      - top=15mm
      - bottom=20mm
    keep-md: false
    keep-tex: false
    toc: true
    fig-pos: "H"
    hyperrefoptions:
    - bookmarksnumbered=true
    toc-title: Contents
    df-print: tibble
    links-as-notes: true
    documentclass: scrbook
    classoption: [twoside=off]
    shift-heading-level-by: 0
    toc-depth: 2
    number-sections: true
    number-depth: 3
    colorlinks: true
  docx:
    toc: false
    number-sections: true
    highlight-style: github
  epub:
    toc: true
    number-sections: true

editor: source
